### ISSUE TITLE
Update URL?

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/book-dp1-public#7]
@jstac currently this book is being served on

dp.quantecon.org

I know there is a `vol2` in the works down the track. Do you think you will use the same companion site for both volumes? Just wondering if we need to set the url to something like

dp1.quantecon.org

**Comment by jstac** [comment]
Hi @mmcky .  Let's use the same site, to keep things simple.

**Comment by mmcky** [comment]
Thanks @jstac sounds good.
